export const ACCOUNT_CURRENCY_LOCAL_STORAGE_KEY = "accountCurrency";
export const ACCOUNT_CURRENCY_LOCAL_STORAGE_DEFAULT_VALUE = "USD";

export const ACCOUNT_BALANCE_LOCAL_STORAGE_KEY = "accountBalance";
export const ACCOUNT_BALANCE_LOCAL_STORAGE_DEFAULT_VALUE = "0";

export const CALCULATOR_LOCAL_STORAGE_KEY = "calculator";
